# Generated by Django 2.1.4 on 2018-12-29 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20181227_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='year',
        ),
    ]
