# Generated by Django 2.1.4 on 2018-12-29 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_remove_link_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='review',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
