# Generated by Django 2.1.4 on 2018-12-30 21:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20181230_1205'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Článek', 'verbose_name_plural': '4. Články'},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Kniha', 'verbose_name_plural': '5. Knihy'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Kategorie', 'verbose_name_plural': '3. Kategorie'},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'Galerie', 'verbose_name_plural': '1. Galerie'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'Obrázek', 'verbose_name_plural': '2. Obrázky'},
        ),
        migrations.AlterModelOptions(
            name='link',
            options={'verbose_name': 'Odkaz', 'verbose_name_plural': '6. Odkazy'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Novinka', 'verbose_name_plural': '7. Novinky'},
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='web.Category', verbose_name='Kategorie'),
        ),
        migrations.AlterField(
            model_name='article',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Datum vytvoření'),
        ),
        migrations.AlterField(
            model_name='article',
            name='date_edited',
            field=models.DateTimeField(auto_now=True, verbose_name='Poslední úprava'),
        ),
        migrations.AlterField(
            model_name='article',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Název'),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='web.Category', verbose_name='Kategorie'),
        ),
        migrations.AlterField(
            model_name='book',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Datum vytvoření'),
        ),
        migrations.AlterField(
            model_name='book',
            name='date_edited',
            field=models.DateTimeField(auto_now=True, verbose_name='Poslední úprava'),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Název'),
        ),
        migrations.AlterField(
            model_name='book',
            name='writer',
            field=models.CharField(max_length=100, verbose_name='Napsal'),
        ),
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.CharField(max_length=4, verbose_name='Rok vydání'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Název'),
        ),
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('a', 'article'), ('b', 'book'), ('l', 'link')], max_length=1, verbose_name='Typ'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Datum vytvoření'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='date_edited',
            field=models.DateTimeField(auto_now=True, verbose_name='Poslední úprava'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Název'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='web.Gallery', verbose_name='Nadřazená galerie'),
        ),
        migrations.AlterField(
            model_name='image',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='image',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Datum vytvoření'),
        ),
        migrations.AlterField(
            model_name='image',
            name='date_edited',
            field=models.DateTimeField(auto_now=True, verbose_name='Poslední úprava'),
        ),
        migrations.AlterField(
            model_name='image',
            name='gallery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='web.Gallery', verbose_name='Galerie'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Název'),
        ),
        migrations.AlterField(
            model_name='link',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='web.Category', verbose_name='Kategorie'),
        ),
        migrations.AlterField(
            model_name='link',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Datum vytvoření'),
        ),
        migrations.AlterField(
            model_name='link',
            name='date_edited',
            field=models.DateTimeField(auto_now=True, verbose_name='Poslední úprava'),
        ),
        migrations.AlterField(
            model_name='link',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Název'),
        ),
        migrations.AlterField(
            model_name='news',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='news',
            name='date_created',
            field=models.DateField(auto_now_add=True, verbose_name='Datum vytvoření'),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
